# Generated by Django 4.2.7 on 2023-11-07 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontdesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('paid', 'paid'), ('not paid', 'not paid')], max_length=300)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontdesk.guest')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounting.invoice')),
            ],
        ),
    ]
