# Generated by Django 4.2.7 on 2023-11-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_invoice_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='invoice',
            new_name='Invoice',
        ),
    ]
